- api/src/models/Book.js
- api/src/models/Comment.js
- api/src/models/User.js
add schema/model for book, user and comment
> Add Schemas/model

- api/src/app.js
- api/src/routes/controllers/Users/getAllUsers.js
- api/src/routes/controllers/Users/getUserById.js
- api/src/routes/controllers/Users/userDelete.js
- api/src/routes/controllers/Users/userPost.js
- api/src/routes/controllers/Users/userUpdate.js
- api/src/routes/controllers/books/bookDelete.js
- api/src/routes/controllers/books/bookPost.js
- api/src/routes/controllers/books/bookUpdate.js
- api/src/routes/controllers/books/getAllBooks.js
- api/src/routes/controllers/books/getBookById.js
- api/src/routes/controllers/getAllUsers.js
- api/src/routes/index.js
organice y seccione las rutas del BakEnd para que sea más intuitivo
> Organización de las rutas BackEnd

- api/src/models/Book.js
- api/src/models/Comment.js
- api/src/models/User.js
change subscriptions from 'free', 'bronce', 'silver', 'gold' to 'free', 'premium'
> change subscription

- api/src/routes/controllers/books/bookUpdate.js
Creación de ruta en el servidor para actualizar libros
> Andres rodriguez

- api/src/routes/controllers/Comments/deleteComment.js
- api/src/routes/controllers/Comments/getCommentsBook.js
- api/src/routes/index.js
corrección de pequeño error en ruta de delete Comment eliminación de ruta para buscar comentarios por sueltos
> Pequeños ajustes

- api/src/routes/controllers/Comments/createCommentBook.js
- api/src/routes/controllers/Comments/updateComment.js
- api/src/routes/controllers/books/bookPost.js
Creamos la ruta y colocamos comprobación de token en caso de estar vacío.
> creación ruta updateComment y pequeños ajustes

- api/src/routes/controllers/books/bookDelete.js
eliminación de chorchetes en delete Book
> pequeña corrección

- api/src/routes/controllers/books/bookDelete.js
- api/src/routes/controllers/books/bookUpdate.js
Agregada la lógica para que solo el usuario creador del libro pueda editar o eliminar el libro
> terminación de las rutas de BookDelete y bookUpdate

- client/src/App.jsx
- client/src/components/Landing/Landing.jsx
- client/src/components/Paginated/paginated.jsx
Recibe como props un array de objetos y la cantidad de items por pagina. De momento solo muestra los titulos de los libros.
> componente paginado

- client/src/components/Home/home.jsx
- client/src/components/OrderAlfab/orderAlfabetico.jsx
- client/src/redux/actions/index.jsx
- client/src/redux/reducer/index.jsx
-creacion del componente para ordenar alfabeticamente los libros
-cambios en action, reduce y home
> Ordenar alfabeticamente los libros

- client/src/components/CreateUser/CreateUser.jsx
- client/src/components/CreateUser/utils.jsx
Creacion de usuario y validaciones para ese form
> componente de creacion de usuarios

- client/src/App.jsx
importacion de la ruta al createUser en App
> ruta del createUser en App

- client/src/assets/main.css
- client/src/assets/tailwind.css
- client/src/components/Home/home.jsx
- client/src/components/Paginated/paginated.jsx
- client/src/index.css
agregue comentario de codigo hardcodeado para probar paginacion en el front y corregi error en landing que impedia cargar la pagina
> Juan felipe velasquez

- client/src/components/Home/home.jsx
- client/src/components/OrderAlfab/orderAlfabetico.jsx
- client/src/redux/actions/index.jsx
-Filtros corregidos
-rutas en las actions corregidas
-saque los console.log para que no molesten
> funcionando filtros

- client/src/components/OrderAlfab/orderAlfabetico.jsx
Corregí estado del useState que había borrado sin querer por eso tiraba error en consola
> corregi el useState

- client/src/assets/main.css
- client/src/components/Bookdetail/Bookdetail.jsx
- client/src/components/CreateUser/CreateUser.jsx
- client/src/redux/actions/index.jsx
- client/src/redux/reducer/index.jsx
funcional detalle de libro y estilo de crear usuario
> funcional front bookdetail e hice estilo de create user

- api/src/controllers/Users/getAllUsers.js
- api/src/controllers/Users/userDelete.js
- api/src/controllers/books/bookPost.js
- api/src/controllers/books/bookUpdate.js
- api/src/controllers/stripe/stripeCheckout.js
- api/src/models/Book.js
- api/src/models/User.js
- api/src/utils/CloudinaryImg.js
User tiene propiedad available en true, la ruta delete te cambia la propiedad a False.
> borrado logico user

- client/src/assets/main.css
- client/src/components/Bookdetail/Bookdetail.jsx
- client/src/components/Bookdetail/Bookdetail.module.css
- client/src/components/Bookdetail/Reviews.jsx
- client/src/components/Landing/Landing.jsx
- client/src/components/Landing/Landing.module.css
- client/src/components/NavBar/NavBar.jsx
- client/src/components/NavBar/NavBar.module.css
- client/src/components/PageOnConstruction/PageOnConstruction.jsx
- client/src/components/PageOnConstruction/PageOnConstruction.module.css
cambio de tailwind a css en los componentes bookdetail, landing, pagonconstruction, navbar
> cambio de tailwind a css 

- api/package-lock.json
- api/package.json
- api/src/controllers/Users/userPost.js
- api/src/emailer/emailer.js
Implementación sencilla del primer envío de emails en la creación de usuarios
> Primer avance para el envío de emails

- api/src/emailer/emailer.js
- client/src/App.jsx
> cambio en emailer require por import

- api/src/emailer/emailer.js
- api/src/emailer/templateNewBook.js
Agregué el template para el correo del nuevo libro creado y la lógica correspondiente para el envío del mismo
> Template newBook

- client/src/components/Login/Login.jsx
- client/src/components/Login/Login.module.css
> estilo loggin

- client/src/components/Bookdetail/Bookdetail.jsx
- client/src/components/Bookdetail/Reviews.jsx
- client/src/components/Landing/index.jsx
para que solo el usuario auter de un libro lo pueda eliminar
> Agrege una validacion 

- api/src/controllers/Comments/createCommentBook.js
- api/src/controllers/books/getBookById.js
- api/src/models/Comment.js
- client/src/components/Bookdetail/Bookdetail.jsx
- client/src/components/Bookdetail/Reviews.jsx
los usuarios logeados ya pueden comentar y poner una calificación a un libro 
también eh creado una lógica para que los usuarios no logeados no puedan comentar
> armando los comentarios

- api/src/controllers/Comments/createCommentBook.js
- api/src/emailer/emailer.js
- client/src/components/Bookdetail/Bookdetail.jsx
agregamos nueva función para el envío de correos a los propietarios de los libros con la creación de nuevos comentarios
> agregada lógica para el envío de correos a nuevos comentarios

- client/src/assets/main.css
- client/src/components/Login/Login.module.css
- client/src/components/Signup/Signup.module.css
- package-lock.json
arreglo error en el width y ubicacion de los botones
> solucion errores de estilo formularios

- client/src/components/DashBoard/CommentEdit/CommentCard.jsx
- client/src/components/DashBoard/CommentEdit/CommentCard.module.css
Render para los comentarios en el form de edicion de coments
> Comments Card

- client/src/components/CssGenerico/CssGenerico.module.css
- client/src/components/Home/home.jsx
- client/src/components/Home/home.module.css
- client/src/components/NavBar/NavBar.jsx
-correccion en home por un div de mas..asi no les tira error
-correccion de dos divs de mas en la navBar y comente el dash porque no va dentro del usuario comun
> correccion error por un div de mas

- .gitignore
- client/src/App.jsx
Cambio de browserRouter a HashRouter
> pequeños cambios para que todo ande perfecto

- client/src/components/DashBoard/CommentEdit/CommentCard.jsx
- client/src/components/DashBoard/CommentEdit/CommentCard.module.css
- client/src/components/DashBoard/CommentEdit/CommentEdit.jsx
Elemento del dash para editar comentarios
> Edicion de comentarios para el dash

- client/src/components/FiltradoGenero/filtradoGenero.jsx
- client/src/components/Home/home.jsx
- client/src/components/OrderAlfab/orderAlfabetico.jsx
> correccion

- api/package-lock.json
- api/package.json
- api/src/controllers/PageViews/PageViews.js
- api/src/routes/PageViews/PageViews.routes.js
- api/src/routes/index.js
- client/index.html
- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/components/DashBoard/PageViews/visitCounter.jsx
- client/src/components/DashBoard/PageViews/visitCounter.module.css
- client/src/redux/actions/index.js
- client/src/redux/reducer/index.js
agregar como variable de entorno la inforomacion .env  del archivo PageViews en a carpeta controllers.
> contador de visitas con ruta de express y diseño front funcional
